parser: babel-eslint
extends:
  - airbnb
  - "plugin:react/recommended"

plugins:
  - babel

env:
  node: true
  browser: true

rules:
  import/no-unresolved: 0
  import/extensions: 0
  react/prop-types: 0
  react/jsx-filename-extension: 0
